version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 557690612191.dkr.ecr.us-east-1.amazonaws.com
      - echo Cloning vProfile code...
      - git clone https://github.com/nedakhodabakhshi/DevOps-Vprofile.git
      - cd DevOps-Vprofile
      - mvn clean install
      - mkdir -p ../vprofile-app/target
      - cp target/vprofile-v2.war ../vprofile-app/target/
      - cd ..
  build:
    commands:
      - echo Building Docker image...
      - chmod +x scripts/build.sh
      - ./scripts/build.sh 
  post_build:
    commands:
      - echo Image pushed successfully.


