version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/vprofile

hooks:
  ApplicationStop:
    - location: deploy/scripts/stop_containers.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy/scripts/start_containers.sh
      timeout: 300
      runas: root
